prometheus:
  prometheusSpec:
    retention: 15d
    nodeSelector:
      kubernetes.io/hostname: monitoring-node
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

grafana:
  nodeSelector:
    kubernetes.io/hostname: monitoring-node
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  adminPassword: "StrongPassword123!"
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: monitoring-node
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

additionalPrometheusRulesMap:
  custom-crashloop-rules:
    groups:
      - name: custom.kubernetes.apps
        rules:
          - alert: kubepodCrashLoopingFast
            expr: |
              max_over_time(
                kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]
              ) >= 1
            for: 10s
            labels:
              severity: warning
            annotations:
              summary: "Pod CrashLoopBackOff Detected"
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in CrashLoopBackOff state for more than 10 seconds."

          - alert: PodOOMKilled
            expr: |
              kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1
            for: 10s
            labels:
              severity: critical
            annotations:
              summary: "Pod OOMKilled"
              description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} was terminated because of OOMKilled."